# This is a basic workflow to help you get started with Actions

name: CI/CD

on: 
  push:
    branches: [ deploy ]

env:
  BUILD_SCRIPT: npm run build

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем зависимости для сборки
      # - name: Install Dependencies
      #   run: npm i
      # Собираем приложение
      # - name: Build Appliction
      #   run: $BUILD_SCRIPT
      # Доставляем собранное приложение на сервер
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }} 
          password: ${{ secrets.PASSWORD }} 
          script: |
            cd ~/sites
            git clone --branch deploy https://github.com/${{ github.repository }}.git
            cd ~/sites/${{ github.event.repository.name }}
            git reset --hard
            git pull origin deploy
            docker-compose build --force-rm --no-cache
            docker-compose up --detach 
            docker builder prune -a -f